#!/usr/bin/env bash
# Open a PR against <owner/repo> that mirrors .github/scripts and
# .github/workflows from the *local* tfman checkout that hosts this skill.
set -euo pipefail
trap 'status=$?; echo "propose-tfman: failed at line $LINENO ($BASH_COMMAND) with exit $status" >&2; exit $status' ERR

usage() {
  cat >&2 <<'EOF'
Usage: propose.sh <owner/repo>

Deploys .github/scripts and .github/workflows from the local tfman checkout
into <owner/repo> on a new branch, commits, pushes, and opens a PR via `gh`.

Run this from inside the tfman repository.

Environment:
  TFMAN_SRC_DIR        Override the source tfman checkout
                       (default: the tfman repo that hosts this skill)
  PROPOSE_BASE_BRANCH  Override the target's base branch
                       (default: detected via `gh repo view`)
  PROPOSE_DRY_RUN      If set non-empty, commit locally but skip push and PR.
EOF
}

if [ $# -lt 1 ]; then usage; exit 2; fi
TARGET="$1"
case "$TARGET" in
  */*) ;;
  *) echo "propose-tfman: target must be in 'owner/repo' form, got: $TARGET" >&2; usage; exit 2 ;;
esac

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SOURCE_ROOT="${TFMAN_SRC_DIR:-$(cd "$SKILL_DIR/../../.." && pwd)}"
WORK_DIR="$SKILL_DIR/tmp/work/${TARGET//\//__}"

if [ ! -d "$SOURCE_ROOT/.github/scripts" ] || [ ! -d "$SOURCE_ROOT/.github/workflows" ]; then
  echo "propose-tfman: source $SOURCE_ROOT does not look like a tfman checkout" >&2
  echo "(.github/scripts or .github/workflows is missing). Set TFMAN_SRC_DIR to a valid tfman checkout." >&2
  exit 2
fi

if [ -d "$SOURCE_ROOT/.git" ]; then
  SOURCE_SHA="$(git -C "$SOURCE_ROOT" rev-parse --short HEAD 2>/dev/null || echo "unknown")"
  # Warn but don't fail on a dirty source: the PR will include the local edits
  # even though the recorded SHA is the clean HEAD before them.
  if [ -n "$(git -C "$SOURCE_ROOT" status --porcelain -- .github/scripts .github/workflows 2>/dev/null)" ]; then
    echo "propose-tfman: warning — $SOURCE_ROOT has uncommitted changes under .github/scripts or .github/workflows." >&2
    echo "The PR will include them, but the recorded SHA ($SOURCE_SHA) won't reflect them." >&2
  fi
else
  SOURCE_SHA="unknown"
fi

mkdir -p "$SKILL_DIR/tmp/work"

if [ -d "$WORK_DIR/.git" ]; then
  echo "Refreshing target clone in $WORK_DIR ..."
  git -C "$WORK_DIR" fetch --prune origin
elif [ -e "$WORK_DIR" ]; then
  echo "Error: $WORK_DIR exists but is not a git clone." >&2
  echo "Inspect and remove it manually, then re-run." >&2
  exit 3
else
  echo "Cloning $TARGET into $WORK_DIR via gh ..."
  gh repo clone "$TARGET" "$WORK_DIR"
fi

if [ -n "${PROPOSE_BASE_BRANCH:-}" ]; then
  BASE_BRANCH="$PROPOSE_BASE_BRANCH"
else
  BASE_BRANCH="$(gh repo view "$TARGET" --json defaultBranchRef --jq .defaultBranchRef.name)"
fi
echo "Base branch: $BASE_BRANCH"

git -C "$WORK_DIR" checkout -B "$BASE_BRANCH" "origin/$BASE_BRANCH" >/dev/null

BRANCH="chore/tfman-update-$(date -u +%Y%m%d-%H%M%S)"
git -C "$WORK_DIR" checkout -B "$BRANCH" >/dev/null

echo "Copying .github/scripts/ from $SOURCE_ROOT ..."
cp -R "$SOURCE_ROOT/.github/scripts/." "$WORK_DIR/.github/scripts/"
echo "Copying .github/workflows/ from $SOURCE_ROOT ..."
cp -R "$SOURCE_ROOT/.github/workflows/." "$WORK_DIR/.github/workflows/"

git -C "$WORK_DIR" add .github/scripts .github/workflows
if git -C "$WORK_DIR" diff --staged --quiet; then
  echo "No changes: $TARGET is already in sync with tfman@$SOURCE_SHA. Nothing to propose."
  exit 0
fi

PR_TITLE="chore: sync tfman scripts & workflows ($SOURCE_SHA)"
git -C "$WORK_DIR" commit -q -m "$PR_TITLE" -m "Sync .github/scripts and .github/workflows from tfman@$SOURCE_SHA."

echo
git -C "$WORK_DIR" --no-pager diff --stat "origin/$BASE_BRANCH..$BRANCH" -- .github/scripts .github/workflows
echo

if [ -n "${PROPOSE_DRY_RUN:-}" ]; then
  echo "Dry run: skipping push and PR creation."
  echo "Local branch '$BRANCH' is committed at $WORK_DIR."
  exit 0
fi

echo "Pushing $BRANCH to origin ..."
git -C "$WORK_DIR" push -u origin "$BRANCH"

PR_BODY=$(cat <<EOF
Sync \`.github/scripts\` and \`.github/workflows\` from tfman@$SOURCE_SHA.

Generated by the \`propose-tfman\` skill.

Review notes:
- Files under \`.github/scripts/\` and \`.github/workflows/\` are now mirrored from the upstream tfman checkout.
- Workflow filenames not present upstream are left alone, but same-named files were overwritten — verify any local customizations you wanted to keep.
- Other tfman adoption pieces (\`environments/\`, \`.terraform-version\`, env files, \`.tfdeps.json\`, \`APPLIERS\`, branch protection) are documented in the tfman README and are out of scope for this PR.
EOF
)
PR_URL="$(gh pr create --repo "$TARGET" --base "$BASE_BRANCH" --head "$BRANCH" --title "$PR_TITLE" --body "$PR_BODY")"
echo "PR created: $PR_URL"
